FROM almalinux:9

# copy the link from google. paste near ADD, now session-01.txt will be save in /tmp/, build the image and run. check  session-01.txt will be in /tmp/
ADD https://raw.githubusercontent.com/daws-90s/notes/refs/heads/main/session-01.txt /tmp/
ADD sample-2.tar /tmp/
CMD ["sleep", "100"]